name: Tool Updating

on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   # We'll run this weekly at 23.00 on Saturday.
  #   - cron:  '0 23 * * 6'
  workflow_dispatch:
    inputs:
      instance:
        description: 'Galaxy Instance URL'
        required: true
        type: choice
        options:
        - galaxy-qa1.galaxy.cloud.e-infra.cz
        - usegalaxy.cz

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint, Fix, and Update
        run: |
            make INSTANCE=$INSTANCE lint
            make INSTANCE=$INSTANCE fix
            make INSTANCE=$INSTANCE update-all
        env:
          INSTANCE: ${{ inputs.instance }}
      - name: Commit files
        run: |
          git config --local user.email "github-bot@github.com"
          git config --local user.name "github-actions[bot]"
          git add *.lock
          git commit -m "Updated all tools ($INSTANCE)" || true
        env:
          INSTANCE: ${{ inputs.instance }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: ${{ github.ref }}
